version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:786081340798:task-definition/nginx:4"
        LoadBalancerInfo:
          ContainerName: "test"
          ContainerPort: 80
